nextcloud/assistant

appinfo/routes.php
lib/Controller/AssistantController.php
lib/Service/AssistantService.php
src/assistant.js
src/components/AssistantForm.vue
src/components/AssistantModal.vue
src/components/RunningEmptyContent.vue
src/components/ScheduledEmptyContent.vue
src/views/TaskResultPage.vue

As discussed with @jancborchardt, here is the synchronous workflow:
We always immediately run the task and wait for the result, showing a spinner in the UI. If users are bored to wait, they can click the schedule button which will stop the sync request and schedule the task just like before.
Sync:
https://github.com/nextcloud/assistant/assets/11291457/1e87f387-289c-44b0-b6c6-aa29b4234a01
Bored:
https://github.com/nextcloud/assistant/assets/11291457/52f7e20d-976a-407c-8c98-b0261935871f

Switch to synchronous workflow

---

CHANGELOG.md
appinfo/info.xml

- Input labels and result warning [#8](https://github.com/nextcloud/assistant/pull/8) @julien-nc
- Implement synchronous workflow and ability to schedule if it's too long [#13](https://github.com/nextcloud/assistant/pull/13) @julien-nc
- Use `@nextcloud/vue` 8 @julien-nc
- Reimplement the task selector with inline buttons and action menu for overflowing ones [#3](https://github.com/nextcloud/assistant/pull/3) @julien-nc
- Set submit button label to "Submit request" when Free prompt is selected @julien-nc
- Fix top-right menu entry style [#4](https://github.com/nextcloud/assistant/issues/4) @julien-nc

Prepare 1.0.2 release

---

CHANGELOG.md
appinfo/info.xml

- Use new runOrSchedule when trying to run a sync task
- Avoid initially selected task to be hidden in the menu
- Set default selected task on first use: free prompt

Prepare 1.0.3

---

src/assistant.js
src/components/AssistantForm.vue
src/components/AssistantModal.vue

refs https://github.com/nextcloud/text/issues/4686
https://github.com/nextcloud/assistant/assets/11291457/5d579c0b-7ee5-4368-97ef-78ff519ff46d
``` js
const params = {
appId: 'plopApp',
identifier: 'idid',
input: 'give me a short summary of a simple settings section about GitHub',
closeOnResult: false,
actionButtons: [
{
label: 'Put in field 1',
title: 'Title 1',
type: 'warning',
iconSvg: cogSvg,
onClick: (task) => { this.field1 = task.output },
},
{
label: 'Put in field 2',
title: 'Title 2',
onClick: (task) => { this.field2 = task.output },
},
],
}
OCA.TPAssistant.openAssistantForm(params)
```
Is it enough to get the task output as parameter of button callbacks? I could refactor a bit and make it possible to get the task itself if necessary.

Integration improvements

---

appinfo/routes.php
lib/AppInfo/Application.php
lib/Controller/AssistantController.php
lib/Controller/SpeechToTextController.php
lib/Controller/Text2ImageController.php
lib/Db/MetaTaskMapper.php
lib/Db/Text2Image/ImageGeneration.php
lib/Db/Text2Image/ImageGenerationMapper.php
lib/Listener/SpeechToText/SpeechToTextResultListener.php
lib/Listener/TaskFailedListener.php
lib/Listener/TaskSuccessfulListener.php
lib/Listener/Text2Image/Text2ImageResultListener.php
lib/Service/AssistantService.php
lib/Service/NotificationService.php
lib/Service/SpeechToText/SpeechToTextService.php
lib/Service/Text2Image/Text2ImageHelperService.php
psalm.xml
src/assistant.js
src/components/AssistantFormInputs.vue
src/components/AssistantTextProcessingForm.vue
src/components/AssistantTextProcessingModal.vue
src/components/TaskList.vue
src/components/TaskListItem.vue
src/components/Text2Image/Text2ImageDisplay.vue
src/components/Text2Image/Text2ImageInlineDisplay.vue
src/main.js
src/views/TaskResultPage.vue
tests/stubs/oc_transcription.php

Add task history as a list that can be toggled at the bottom of the assistant.
The list only contains tasks of the currently selected type.
With the context menu, tasks can be deleted, canceled (when status is scheduled) and repeated (try again if they were successful).
Clicking on a task item loads it in the form (inputs + output) so it can be viewed, edited and launched again.
The task list is visible in the main assistant modal, the one when opening a task result from a notification and in the dedicated assistant page showing a task result.
@nimishavijay @jancborchardt I will deploy this on tech-preview soon. Any first feedback?

Add task history

---

README.md
appinfo/info.xml
appinfo/routes.php
lib/Controller/AssistantApiController.php
lib/Controller/AssistantController.php
lib/Controller/SpeechToTextApiController.php
lib/Controller/SpeechToTextController.php
lib/Controller/Text2ImageApiController.php
lib/Controller/Text2ImageController.php
lib/Service/AssistantService.php
lib/Service/SpeechToText/SpeechToTextService.php
lib/Service/Text2Image/Text2ImageHelperService.php
src/assistant.js
src/components/AssistantFormInputs.vue
src/components/AssistantTextProcessingForm.vue
src/components/TaskList.vue
src/components/Text2Image/Text2ImageDisplay.vue
src/components/Text2Image/Text2ImageInlineDisplay.vue
src/views/SpeechToText/SpeechToTextCustomPickerElement.vue
src/views/TaskResultPage.vue
src/views/Text2Image/Text2ImageCustomPickerElement.vue
src/views/Text2Image/Text2ImageGenerationPage.vue

* mention more assistant features in the readme and info.xml
* move many endpoints to OCS (anticipate integration by other apps)
* Compute the task type list on the backend side so we can check if there actually are available providers

Check all task types availability and improve app description

---

lib/Listener/BeforeTemplateRenderedListener.php
src/components/AdminSettings.vue
src/components/AssistantTextProcessingForm.vue
src/components/NoProviderEmptyContent.vue

* Still show the top-right assistant icon if no provider is available
* If task type list is empty (so we know there is no provider available), show this in the assistant modal to admins:
and this to non-admins:
@jancborchardt Any suggestion for the title, description and admin hint?

Show empty content if no AI provider was found

---

appinfo/routes.php
lib/Controller/FreePromptController.php
lib/Controller/PreviewController.php
lib/Service/AssistantService.php
lib/Service/PreviewService.php
psalm.xml
src/components/AssistantFormInputs.vue
src/components/ContextChat/ContextChatInputForm.vue

Design feedback required on the selector UI (Select File/Folder-Select Providers). It looks a bit too big imo. The same selector is present in speech-to-text UI so that would also need to be changed to maintain consistency. Something less obstructing/with less occupancy on the dialog is what I imagine would be a good fit.
@nimishavijay @jancborchardt

enh: custom UI for scoped context chat

---

src/components/AssistantTextProcessingForm.vue
src/components/TaskTypeSelect.vue

* reset the form result if the user selects another task
* fix submit button label (avoid having "try again" after resetting the result)

Fix result display after task type change

---

.github/workflows/openapi.yml
.gitignore
composer.json
composer.lock
docs/README.md
docs/ocs-api.md
docs/web-integration.md
lib/Capabilities.php
lib/Controller/AssistantApiController.php
lib/Controller/SpeechToTextApiController.php
lib/Controller/Text2ImageApiController.php
lib/Service/SpeechToText/SpeechToTextService.php
openapi.json
src/assistant.js
src/main.js
src/views/TaskResultPage.vue

* add developer doc in `/docs`
* write and generate OpenAPI specs
* make sure frontend helper functions are not broken, call new ones in the old ones
* harmonize STT scheduling logic with the rest (properly schedule, factorize frontend code, return task in the API etc...)

Developer doc

---

src/components/AssistantTextProcessingForm.vue
src/components/TaskList.vue

closes #62
The history task list is retrieved after the history button is clicked so we can't hide the button if the history is empty.
But we can show an empty content:

Add empty content when history is empty

---

CHANGELOG.md
appinfo/info.xml

- OpenAPI specs
- Support for NC 30
- Developer and user docs @julien-nc [#57](https://github.com/nextcloud/assistant/pull/57) [#61](https://github.com/nextcloud/assistant/pull/61)
- Node and eslint workflows @kyteinsky [#60](https://github.com/nextcloud/assistant/pull/60)
- Add empty content when history is empty @julien-nc [#63](https://github.com/nextcloud/assistant/pull/63)
- reset input/output form if the task type is changed by the user @julien-nc [#54](https://github.com/nextcloud/assistant/pull/54)
- create tmp folder to store docs as 0700 @kyteinsky [#64](https://github.com/nextcloud/assistant/pull/64)

Prepare 1.0.8 release

---

lib/Service/AssistantService.php

fix: use ITempManager instead of manually handling temp files

---

appinfo/routes.php
lib/Controller/AssistantController.php
lib/Db/MetaTask.php
src/assistantPage.js
src/taskResultPage.js
src/views/AssistantPage.vue
templates/assistantPage.php
webpack.js

This makes the task result page able to show an empty task. It is reachable at `apps/assistant/`. This might be useful for clients that want to open the "raw" assistant in a browser.

Add standalone assistant page

---

docs/developer/web-integration.md
src/assistant.js

So it's possible to provide all initial inputs.

Add 'inputs' object param to OCA.Assistant.openAssistantForm

---

CHANGELOG.md
appinfo/info.xml

- support RTF files @julien-nc [#66](https://github.com/nextcloud/assistant/pull/66)
- new assistant standalone page @julien-nc [#72](https://github.com/nextcloud/assistant/pull/72)
- use ITempManager instead of manually handling temp files @kyteinksy [#71](https://github.com/nextcloud/assistant/pull/71)
- fix audio transcription smart picker not setting appId and identifier params in the schedule request

prepare 1.0.9

---

lib/Controller/ChattyLLMController.php
lib/Db/ChattyLLM/SessionMapper.php
src/components/ChattyLLM/ChattyLLMInputForm.vue
src/components/ChattyLLM/ConversationBox.vue
src/components/ChattyLLM/EditableTextField.vue
src/components/ChattyLLM/Message.vue
src/components/ChattyLLM/MessageActions.vue

+ edit action buttons alignment
+ security fixes in chatty ui controller

button disable fix + make fallback strings same for translation ease

---

CHANGELOG.md

- Ability to cancel a task while waiting for results in the assistant @julien-nc [#97](https://github.com/nextcloud/assistant/pull/97)
- Set min and max NC version to 30
- Switch from text processing to task processing API @julien-nc [#97](https://github.com/nextcloud/assistant/pull/97)
- UI/UX improvements @julien-nc [#97](https://github.com/nextcloud/assistant/pull/97)
- Avoid blocking a Php runner waiting for ChattyUI tasks to finish, poll in the frontend like the other task types @julien-nc [#97](https://github.com/nextcloud/assistant/pull/97)
- Get rid of the smart picker custom components, open the assistant instead @julien-nc [#97](https://github.com/nextcloud/assistant/pull/97)
- Simplify image generation, let users download or share result images directly in the assistant …

prepare v2.0.1

---

CHANGELOG.md
appinfo/info.xml

- Support for Enum field type @julien-nc
- Support action buttons when opening a task with OCA.Assistant.openAssistantTask @julien-nc
- Hide 'choose file' button in context chat input form @julien-nc
- Fix short input displayed when a task is scheduled @julien-nc
- Fix style issues in standalone page @julien-nc

Prepare 2.0.2

---

src/components/AssistantTextProcessingForm.vue
src/components/TaskTypeSelect.vue

This makes task types more discoverable.
| Before | After |
| ---- | ----- |
| ![image](https://github.com/user-attachments/assets/323d0b92-fde0-48e8-9faf-8ae2bbd18d3e) | ![image](https://github.com/user-attachments/assets/2474561a-ea64-4d99-9fb4-7ad2eace84d7) |

Show all task types inline

---

src/components/fields/ListOfTextsField.vue
src/components/fields/TextField.vue

Because they can contain trailing new lines.

Trim text values

---

lib/AppInfo/Application.php

closes #104 
It is still possible to include the user's display name in the instruct prompt by using `{user}` in the prompts in the AI admin settings.

[Chat] Do not send the user's display name in the instruct prompts by default

---

lib/AppInfo/Application.php
lib/Settings/Admin.php
package-lock.json
package.json
src/components/AdminSettings.vue
src/components/fields/AudioRecorderWrapper.vue

* Cleanup old constants and an admin setting field that are not used anymore
* Update npm pkgs

Cleanup old constants

---

src/assistant.js

Which breaks opening a task result from a notification.

Fix missing destructured param when calling openAssistantTask

---

CHANGELOG.md
appinfo/info.xml

- Do not send the user's display name in the chat instruct prompts by default @julien-nc [#116](https://github.com/nextcloud/assistant/pull/116)
- Only show 2 digits for the task progress @julien-nc [#119](https://github.com/nextcloud/assistant/pull/119)
- Missing destructured param when calling openAssistantTask @julien-nc [#120](https://github.com/nextcloud/assistant/pull/120)
- Adjust to html header structure change in 31

Prepare v2.0.4

---

src/assistant.js
src/components/AssistantTextProcessingModal.vue
src/components/RunningEmptyContent.vue
src/components/ScheduledEmptyContent.vue
src/components/TaskListItem.vue
src/views/AssistantPage.vue

Add back buttons in both running confirmation and scheduled confirmation screens after a task has been launched.
Clicking this buttons brings the user back to the input form. The potential output (if the user was "trying again") is cleared.
Small extra improvement: Close the task history item menu when canceling a task.

Add back buttons after launching a task

---

src/assistant.js
src/views/AssistantPage.vue

The "try again" action (in the task history items) was broken. It was using a wrong prop from the task object, resulting in not setting the task type parameter when calling the scheduling endpoint.

Fix incorrect task type prop set when trying again

---

src/components/AssistantHeaderMenuEntry.vue

It was based on the primary color instead of the background color.
So if the primary color was dark and the background was light, the assistant navigation icon was light and vice versa.

Fix navigation icon color

---

CHANGELOG.md
appinfo/info.xml

- Add a personal settings section listing the configured backends @marcelklehr [#134](https://github.com/nextcloud/assistant/pull/134)
- Report task ID in more failure messages @marcelklehr [#137](https://github.com/nextcloud/assistant/pull/137)
- Missing worker policy when launching assistant @smarinier [#139](https://github.com/nextcloud/assistant/pull/139)
- Incorrect task type prop set when trying again @julien-nc [#144](https://github.com/nextcloud/assistant/pull/144)
- Fix navigation icon color @julien-nc [#145](https://github.com/nextcloud/assistant/pull/145)

Prepare 2.1.1

---

docs/developer/web-integration.md
lib/Controller/AssistantApiController.php
lib/Service/AssistantService.php
openapi.json
src/components/AssistantTextProcessingForm.vue

This will be helpful to make file actions (in the Files app).
The `OCA.Assistant.openAssistantForm` function now accepts inputs like 
``` js
{ input: { fileId: 123 } }
```
or
``` js
{ input: { filePath: '/path/to/file.txt' } }
```
and the parsed file content will be inserted in the input field on the fly.

Allow to pass file ID/path as initial input text field value

---

lib/Notification/Notifier.php

This can happen if there is a (non-dismissed) notification for a task with a task type that is not available anymore (because the related app has been disabled for example).

fix(notifier): check if task type is there before getting its name

---

CHANGELOG.md

- Agency support @julien-nc [#169](https://github.com/nextcloud/assistant/pull/169)
- Use Text2TextChat in the chatty UI when the Agency task type is not available @julien-nc [#169](https://github.com/nextcloud/assistant/pull/169)
- Switch to IAppConfig @julien-nc [#147](https://github.com/nextcloud/assistant/pull/147)
- Avoid anthropomorphism @marcelklehr [#148](https://github.com/nextcloud/assistant/pull/148)
- Add confirmation dialog before deleting a conversation @julien-nc [#160](https://github.com/nextcloud/assistant/pull/160)
- Allow to pass file ID or path as initial input text field value @julien-nc [#161](https://github.com/nextcloud/assistant/pull/161)
- Fix polling when switching sessions in the frontend, prevent scheduling multiple llm tasks for one session @julien-nc …

prepare 2.2.0

---

lib/Controller/AssistantController.php
lib/Listener/BeforeTemplateRenderedListener.php
src/assistant.js
src/components/AssistantTextProcessingForm.vue
src/main.js

This adds a short loading time before task types will be shown in the assistant modal. Ideas how to prevent that very welcome :)

feat: save default target language & set detect_language as origin default

---

lib/Service/AssistantService.php
tests/psalm-baseline.xml

They are not useful for the user directly.

Hide ChatWithTools and ContextAgentInteraction task types

---

appinfo/info.xml
lib/Migration/Version020201Date20250120174409.php

closes #174
For some reason, some app config values were stored as integers. I think we never did that in the app. There might have been a server migration or repair step that sets the type to integer when the stored value looks like an integer.
We historically store all values as string (because we were using IConfig) and kept that even with typed values in IAppConfig. I'm pretty sure we didn't mess with those values in the Assistant.

Fix config value types for some bools and ints we store

---

CHANGELOG.md
appinfo/info.xml

- Save default target language & set detect_language as origin default @janepie @julien-nc [#167](https://github.com/nextcloud/assistant/pull/167)
- Hide ChatWithTools and ContextAgentInteraction task types @julien-nc [#172](https://github.com/nextcloud/assistant/pull/172)
- Add reuse compliance @AndyScherzinger [#163](https://github.com/nextcloud/assistant/pull/163)
- Fix config value types for some bools and ints we store @julien-nc [#174](https://github.com/nextcloud/assistant/pull/174)

Prepare 2.3.0

---

src/components/fields/ImageDisplay.vue

Instead of cropping the image, forcing the width to be 200px.
We could also use `object-fit: cover` to keep a square preview and just show a part of the image.
closes #182

Show image results full width

---

appinfo/routes.php
lib/Controller/AssistantApiController.php
lib/Service/AssistantService.php
openapi.json
src/components/fields/AudioDisplay.vue
src/components/fields/ImageDisplay.vue
src/components/fields/ListOfMediaField.vue
src/components/fields/MediaField.vue
tests/psalm-baseline.xml

* Use new endpoint to download task output files. This one deduces the mimetype from the file content. (So browsers append a type extension to the file name when downloading)
* Cache download and preview endpoint responses
* Use the preview endpoint to display result images (300x300) instead of getting the complete image
* Generate openapi specs
* Fix psalm issues

Improve media download and preview endpoints

---

src/components/AssistantTextProcessingModal.vue

fixes #118 
keeps the string as labelId for accessibility reasons

Fix: delete assistant modal title

---

src/components/fields/TextInput.vue

For some reason left must be unset when right is defined and the other way around.
cc @DaphneMuller

Fix choose file button position with RTL languages

---

src/components/AdminSettings.vue

Fix h2 and checkbox info style in the admin settings

---

lib/Notification/Notifier.php
lib/Service/AssistantService.php

fix: input text and action button fix in context chat

---

lib/Controller/ChattyLLMController.php
package-lock.json
package.json
src/components/ChattyLLM/AgencyAction.vue
src/components/ChattyLLM/AgencyActions.vue
src/components/ChattyLLM/AgencyConfirmation.vue

For actions with a lot of params:
More will come.

Adjustments of agency confirmation style

---

CHANGELOG.md

- Show image results full width @julien-nc [#183](https://github.com/nextcloud/assistant/pull/183)
- Use new assistant endpoint to download task output files with mimetype detection, use preview endpoint to display image results @julien-nc [#184](https://github.com/nextcloud/assistant/pull/184)
- Improve agency action confirmation style+design @julien-nc [#194](https://github.com/nextcloud/assistant/pull/194)
- Update npm pkgs to fix NcSelect with right-to-left languages @janepie [#185](https://github.com/nextcloud/assistant/pull/185)
- Make assistant modal 'dark' @janepie [#180](https://github.com/nextcloud/assistant/pull/180)
- Fix choose file button position with RTL languages @julien-nc [#186](https://github.com/nextcloud/assistant/pull/186)
- Fix UI issues for Context Chat @kyteinsky …

prepare 2.4.0

---

src/components/ChattyLLM/ChattyLLMInputForm.vue

Fix: saving Chat with AI as last task type

---

composer.json
composer.lock
lib/Service/AssistantService.php

When a task output file is shared from the assistant UI, the file extension is guessed from the mimetype. More types are now supported.
For the download endpoint, setting the mimetype correctly in the response headers is enough for browsers to guess the extension in the suggested file name.

Better naming of shared output files, support more mime types

---

src/components/ChattyLLM/Message.vue

Override NcRichText link resolving to support markdown links.
This currently produces a lot of warnings because the `references` prop of `<NcRichText>` is declared as Object but the implementation actually expects an array. I'll fix that in nc/vue.

Support markdown links preview in chat UI

---

src/components/ChattyLLM/ConversationBox.vue
src/components/ChattyLLM/InputArea.vue
src/components/ChattyLLM/LoadingPlaceholder.vue

Resolves #214. The [LoadingPlaceholder component](https://github.com/nextcloud/spreed/blob/main/src/components/UIShared/LoadingPlaceholder.vue) from the Talk app was copied and minimally adapted to fit the chat UI. Also, the message input field already displays `Processing...` while the message is being generated, so I don't think there is a need for additional text underneath the placeholder either.

feat(ChattyLLM): replace loading spinner with skeleton message

---

appinfo/routes.php
lib/AppInfo/Application.php
lib/Controller/AssistantApiController.php
lib/Listener/BeforeTemplateRenderedListener.php
lib/Listener/TaskOutputFileReferenceListener.php
lib/Reference/TaskOutputFileReferenceProvider.php
lib/Service/AssistantService.php
openapi.json
src/components/AssistantTextProcessingModal.vue
src/components/fields/FileDisplay.vue
src/components/fields/MediaField.vue
src/taskOutputFileReference.js
src/views/TaskOutputFileReferenceWidget.vue
vite.config.ts

2 things:
* Add a reference provider and a link preview widget for https://nextcloud.local/ocs/v2.php/apps/assistant/api/v1/task/42/output-file/398/download and https://nextcloud.local/ocs/v2.php/taskprocessing/tasks/42/file/398 links. The widget actually uses the same component we use to display output files in the assistant form (`<MediaField>`)
* Click on the MediaField preview now saves the files (in the /Assistant dir) and opens the Viewer on the file
Remaining issue: The Viewer is not displayed on top of the assistant modal. Everything is fine if we open the viewer from a link widget in Talk, or from the assistant standalone page, but no luck if the assistant itself is already in a modal.
**Solution**: Change the NcModal `container` prop to `#content`. The Viewer is then displayed …

Task output file download link reference

---

src/assistant.js
src/components/AssistantTextProcessingModal.vue
src/components/RunningEmptyContent.vue
src/views/AssistantPage.vue

Resolves #212. Formatting and text may still need some adjusting, though.

feat: display expected task runtime when running

---

src/components/AssistantFormInputs.vue
src/components/AssistantTextProcessingForm.vue
src/components/ChattyLLM/InputArea.vue
src/components/fields/TaskTypeField.vue
src/components/fields/TaskTypeFields.vue
src/components/fields/TextField.vue
src/components/fields/TextInput.vue
src/mixins/isMobile.js

Resolves #210. This enables the Ctrl+Enter shortcut to submit a prompt in the text input field to the AI.

feat: schedule task on text prompt input submit event

---

appinfo/info.xml
lib/Db/ChattyLLM/Message.php
lib/Listener/BeforeTemplateRenderedListener.php
lib/Listener/ChattyLLMTaskListener.php
lib/Migration/Version020500Date20250425125359.php
lib/ResponseDefinitions.php
lib/Service/AssistantService.php
openapi.json
src/components/ChattyLLM/ChattyLLMInputForm.vue
src/components/ChattyLLM/ConversationBox.vue
src/components/ChattyLLM/Message.vue

The info button shows where the information the Agent used comes from
Defined per tool, every source will only be listed once
Needs https://github.com/nextcloud/context_agent/pull/22 to show sources

Feat: Information Source info in Chat UI

---

src/assistant.js
src/components/AssistantFormInputs.vue
src/components/AssistantTextProcessingForm.vue
src/components/AssistantTextProcessingModal.vue
src/components/TaskList.vue
src/components/TaskListItem.vue
src/views/AssistantPage.vue

Resolves #211. This is a large change that involves reorganizing the locations and properties of multiple components, so there will likely still be some visual and/or functional bugs that need ironing out. Feel free to add such bugs as to-do items here if you find any. Most tasks aside from context chat or context agent have been lightly tested.
Some missing items:
- ~move (and possibly reorganize) the loading and scheduled screens~ (de-scoped in the meantime)

feat: task layout design update

---

src/components/fields/ImageDisplay.vue
src/components/fields/ListOfMediaField.vue
src/components/fields/MediaField.vue

It was only done for simple/single output media items. This is now the case for output media list (list of images and files).
The only task type with an output media list is "image generation" for now.
[Kooha-2025-05-07-11-31-48.webm](https://github.com/user-attachments/assets/e22ee3df-302d-495e-86d4-2b0a9e753a4d)

Open output media list items in the viewer

---

src/components/AssistantFormInputs.vue
src/components/AssistantTextProcessingForm.vue

Resolves #217.
Continuing discussion from #227:
> The only thing that is not working is the preservation of the "input" input because the default values are applied in 2 places:
> 
> * AssistantTextProcessingForm::onTaskTypeUserChange (where the input is preserved)
> 
> * AssistantFormInputs::watch::selectedTaskType
> 
> and if the second one happens after the first, the input field is cleared.
I'm not sure if `AssistantFormInputs::watch::selectedTaskType` has any purpose anymore, now that I think about it, especially now with the addition of the `TranslateForm`. Removing it fixed the issue for me.

feat: keep input prompt when switching task types

---

lib/Service/AssistantService.php
src/components/AssistantFormInputs.vue
src/components/AssistantFormOutputs.vue
src/components/ContextChat/ContextChatInputForm.vue
src/components/ContextChat/ContextChatSearchOutputForm.vue
src/components/ContextChat/ContextChatSource.vue

This is related with 
* https://github.com/nextcloud/context_chat/pull/129
Custom forms:
* Output: one NcRichText per source
* Input: reuse the classic context chat input form but remove the "source" scope type and add the "limit" number field

Add custom input and output forms for context_chat_search

---

src/components/AssistantTextProcessingForm.vue

Loading spinner will spin forever

fix: assistant fails to load when text2text disabled but other task exists

---

src/components/AssistantTextProcessingForm.vue

Preserve inputs when switching task type only if it was text and it goes in a text field.

Fix input preservation

---

package-lock.json
package.json
src/audioUtils.js
src/components/AssistantFormOutputs.vue
src/components/AssistantHeaderMenuEntry.vue
src/components/TaskList.vue
src/components/TaskListItem.vue
src/components/fields/AudioDisplay.vue
src/components/fields/AudioRecorderWrapper.vue
src/components/fields/ListOfTextsField.vue
src/mixins/isMobile.js
src/utils.js
src/views/ImageResultCustomPickerElement.vue
src/views/TextResultCustomPickerElement.vue

* Fix issue when there is a 'output' output field that is not text (a check in a computed crashes)
* Nicer task list item display when there is only audio input or output 
* Emphasize audio outputs with the same border as for text output 
* Change how we record audio: convert to wav and then to mp3 to make sure it's small and compatible with many APIs/tools
* Vue 3 migration mistake: beforeDestroy is now beforeUnmount
* Fix style for "list of text" fields
* Fix item deletion for "list of text" fields

UI adjustments

---

lib/Controller/ChattyLLMController.php

Extracts from nextcloud.log
```
"Exception": "OC\\DB\\Exceptions\\DbalException",
"Message": "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'sources' doesn't have a default value",
"message": "Failed to create a chat session",
"exception": {
"query": "INSERT INTO `*PREFIX*assistant_chat_msgs` (`session_id`, `role`, `content`, `timestamp`) VALUES(:dcValue1, :dcValue2, :dcValue3, :dcValue4)"
},
"CustomMessage": "Failed to create a chat session"
```

fix: explicitly set default sources when creating new session

---

lib/Controller/ChattyLLMController.php
lib/Migration/Version020200Date20241218145833.php
lib/Migration/Version020500Date20250425125359.php
lib/Migration/Version020600Date20250704145036.php

MySQL does not allow setting a default for BLOB, TEXT, GEOMETRY or JSON column.
ref: https://github.com/nextcloud/assistant/pull/295, https://github.com/nextcloud/assistant/pull/295#issuecomment-3062249762

chore: do not set a default for longtext db fields

---

lib/Service/TaskProcessingService.php
src/components/fields/TextInput.vue
src/constants.js
src/files/fileActions.js

Resolves: #321 
Also changes the audio file types to be anything in VALID_AUDIO_MIME_TYPES so there aren't 2 separate lists keeping track of this.

feat: add support for more file types to file actions

---

CHANGELOG.md

- Audio chat for the Chat UI @julien-nc [#292] (https://github.com/nextcloud/assistant/pull/292)
- Param in openAssistantForm to restrict which task types are displayed @julien-nc [#287] (https://github.com/nextcloud/assistant/pull/287)
- Categories and icons for task types @lukasdotcom [#311] (https://github.com/nextcloud/assistant/pull/311)
- File actions for text, audio and markdown files @julien-nc [#312] (https://github.com/nextcloud/assistant/pull/312)
- UI hint when task is taking too long @lukasdotcom [#315] (https://github.com/nextcloud/assistant/pull/315)
- Generate image action in "New file" menu @andrey18106 [#322] (https://github.com/nextcloud/assistant/pull/322)
- Support for more file types to file actions @lukasdotcom [#326] …

Prepare release v2.6.0

---

CHANGELOG.md

- Fix adding attachments and sources with notNull=true and no default value making the migration crash for postgres @julien-nc [#335](https://github.com/nextcloud/assistant/pull/335)

Prepare 2.6.1

---

lib/Listener/BeforeTemplateRenderedListener.php
package-lock.json
src/components/AssistantHeaderMenuEntry.vue
src/components/AssistantTextProcessingForm.vue
src/components/AssistantTextProcessingModal.vue
src/components/TaskTypeSelect.vue

closes #347
If we want to keep supporting NC 30 and 31, we need to be careful with this custom style that is not included in NC < 32. There is now a `use-modern-style` initial state injected to decide if we use the new css vars or not.
@marcoambrosini We can't use `NcAssistantButton` because
* NcActions is not flexible enough
* Even if we could use it to replace our `NcButton` in some places, this component does not allow to use a custom icon so we're stuck with the assistant one but we want the category one
So I went with custom styling using the css variables.
I tried to replicate the gradient in the NcAssistantButton component but this is done by using a gradient background in an element wrapping the NcButton. Here we directly use the button, no wrapping element. I couldn't find a way …

Use new assistant theme

---

CHANGELOG.md
appinfo/info.xml

- Rename ai settings to assistant @lukasdotcom [#333](https://github.com/nextcloud/assistant/pull/333)
- Improve sticker generation @lukasdotcom [#331](https://github.com/nextcloud/assistant/pull/331)
- Replace mdi download icon with Material Symbols variant @AndyScherzinger [#348](https://github.com/nextcloud/assistant/pull/348)
- Improve style and use new assistant components @julien-nc [#349](https://github.com/nextcloud/assistant/pull/349)
- Only show the group file action if necessary @julien-nc [#342](https://github.com/nextcloud/assistant/pull/342)

Prepare 2.7.0

---

lib/Controller/ChattyLLMController.php

When checking if the last attachment is an audio one right before scheduling the task to generate a new message.
This goes well with some Php configs that are not strict. It can also crash.

Prevent accessing array index on null

---

src/assistant.js
src/components/ChattyLLM/ChattyLLMInputForm.vue

closes #355
* Fix stop polling when closing the assistant while polling a classic task
* Fix stop polling when closing the assistant while polling a message generation in the chat UI (wrong component method name, `onDestroy()` does not exist anymore in vue3. We now use `beforeUnmount()`.
* Bonus: Get rid of the eslint warning about the `axios.isCancel` import

Fix stop polling when needed

---

src/components/ChattyLLM/LoadingPlaceholder.vue
src/components/icons/AssistantIcon.vue

deactivates the icon animation and the placeholder movement when reduce-motion OS setting is set
CSS feature and how to activate it described here: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

Feat: respect reduced-motion settings
